# --- TACTICAL WORKSTATION CORE CONFIG ---

# Import Modularity Layers
source = ~/.config/hypr/configs/theme.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/rules.conf

# Autostart Core Components
exec-once = waybar
# Target your dot-grid/topographic image file
exec-once = hyprpaper

# Environment Variables for Paravirtualization Stability
env = WLR_NO_HARDWARE_CURSORS,1
env = XDG_CURRENT_DESKTOP,Hyprland
