# Tech-Brutalism Theme Matrix

general {
    gaps_in = 3
    gaps_out = 6
    border_size = 1
    
    # High-contrast instrumentation colors
    col.active_border = rgb(a1a1aa)   # Cold Slate White
    col.inactive_border = rgb(27272a) # Muted Obsidian Gray

    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 0       # Absolutely no rounded corners
    drop_shadow = false # Flat visual pipeline
    
    blur {
        enabled = false # Maximize performance inside QEMU
    }
}

animations {
    enabled = true
    # Instantaneous linear tracking curve mimicking telemetry displays
    bezier = sharpLinear, 0.1, 1.0, 0.1, 1.0
    
    animation = windows, 1, 2, sharpLinear, popin
    animation = workspaces, 1, 3, sharpLinear, slidevert
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = rgb(18181b) # Deep zinc base
}
